# Generated by Django 3.0.8 on 2022-11-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Цифра')),
                ('symbol', models.CharField(max_length=1, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'Справочник классов',
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_group', models.DateField(verbose_name='Дата создания группы учеников')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Група учеников',
                'verbose_name_plural': 'Группы учеников',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'Справочник предметов',
            },
        ),
        migrations.CreateModel(
            name='RatingItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Статус оценки')),
            ],
            options={
                'verbose_name': 'статус оценки',
                'verbose_name_plural': 'Справочник статусов оценок',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2')], verbose_name='Оценка')),
                ('created', models.DateField(verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('attend', models.BooleanField(null=True, verbose_name='Был(а)  на уроке')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.GroupStudent', verbose_name='Наименование класса')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Lesson', verbose_name='Предмет')),
                ('score_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.RatingItemStatus', verbose_name='Статус оценки')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'Оценки',
            },
        ),
    ]
