# Generated by Django 3.0.8 on 2022-11-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20221128_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='attend',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], max_length=15, null=True, verbose_name='Был(а)  на уроке'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.SmallIntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2')], null=True, verbose_name='Оценка'),
        ),
    ]
