# Generated by Django 3.0.8 on 2022-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20221129_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.SmallIntegerField(blank=True, choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2')], null=True, verbose_name='Оценка'),
        ),
    ]
