# Generated by Django 3.0.8 on 2022-11-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20221129_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='attend',
            field=models.CharField(blank=True, choices=[('Нет', 'Нет'), ('Да', 'Да')], max_length=15, null=True, verbose_name='Был(а)  на уроке'),
        ),
    ]
